version: 2
jobs:
  build:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install node
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v8
            nvm alias default v8
            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - run:
          name: Install dependencies
          command: npm install --quiet
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Login to Docker
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Test of hello-engine
          command: ./test/test-hello-engine.sh
      - run:
          name: Test of hello-data
          command: ./test/test-hello-data.sh
      - run:
          name: Install Chrome
          background: true
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb; sudo apt-get -fy install
      - run:
          name: Test of hello-visualization
          command: ./test/test-hello-visualization.sh
